config/routes.rb
Bandrockr::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin-metal', as: 'rails_admin'
  get "admin" => "admin#index"

  resources :gigs

  resources :photos

  resources :tracks

  resources :albums

  resources :links

  resources :members

  resources :band_profiles

  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :tracks

    def self.latest
        order("release_date DESC").first
    end
end

app/models/band_profile.rb
class BandProfile < ActiveRecord::Base
	has_many :links
end

app/models/gig.rb
class Gig < ActiveRecord::Base
	def self.next
        where("date > ?", Date.today).order("date ASC").first
    end
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :band_profile
  belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base
	has_many :links
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	default_scope { order("created_at DESC") }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :title_album
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  validates_presence_of :name

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  # GET /gigs
  # GET /gigs.json
  def index
    @gigs = Gig.all
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
  end

  # GET /gigs/new
  def new
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(gig_params)

    respond_to do |format|
      if @gig.save
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gig }
      else
        format.html { render action: 'new' }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1
  # PATCH/PUT /gigs/1.json
  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gig
      @gig = Gig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gig_params
      params.require(:gig).permit(:title, :date, :start_time, :finish_time, :location, :street_address, :suburb, :tickets_url)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/admin/_band_links.html.erb
<h3>Band links</h3>
        <% if @band_profile.links.count > 0 %>
                <h3><%= @band_profile.name %>'s Links</h3>
                <% @band_profile.links.each do |link| %>
                        <p><%= link_to link.title, link.url %></p>
                <% end %>
        <% end %>
        <p><%= link_to "Add links", new_link_path, class: 'btn btn-warning' %></p>

app/views/admin/_band_profile.html.erb
<h2><%= @band_profile.name %>'s Profile</h2>
        <p><strong>Name:</strong> <%= @band_profile.name %></p>
        <p><strong>Info:</strong> <%= @band_profile.info %></p>
        <p><%= link_to "Edit band profile", edit_band_profile_path(@band_profile), class: 'btn btn-warning' %></p>

app/views/admin/_no_profile.html.erb
<div class="alert alert-warning">
                <h4>You don't have a profile yet! Create your band profile now!</h4>
                <br>
                <%= link_to "Create profile", new_band_profile_path, class: 'btn btn-success' %>
        </div>
        

app/views/admin/index.html.erb
<h1>Welcome to BandRockr!</h1>

<% if !@band_profile %>

        <%= render 'no_profile' %>

<% else %>

        <%= render 'band_profile' %>


        <hr>
        <%= render 'band_links' %>

        <hr>

        <h3>Band members</h3>
        <% if @members.count > 0 %>

                <% @members.each do |member| %>
                        <div class="container">
                                <%= image_tag member.image, class: "pull-left" %>
                                <p><strong><%= member.name %></strong></p>
                                <p><%= member.info %></p>
                                <p><%= link_to "Edit member", edit_member_path(member), class: 'btn btn-warning' %></p>
                                <% if member.links.count > 0 %>
                                        <% member.links.each do |link| %>
                                                <p><%= link_to link.title, link.url %></p>
                                        <% end %>
                                <% end %>
                                <p><%= link_to "Add links", new_link_path, class: 'btn btn-warning' %></p>
                        </div>
                <% end %>
        <% end %>
        <p><%= link_to "Add band members", new_member_path, class: 'btn btn-warning' %></p>

        <hr>
        <h2>Gigs</h2>
        <% if @gigs.count > 0 %>


                <table class="table table-hover">
                        <thead>
                                <tr>
                                        <th>Gig name</th>
                                        <th>Date</th>
                                        <th>Location</th>
                                        <th>Status</th>
                                        <th></th>
                                        <th></th>
                                </tr>
                        </thead>
                        <tbody>
                                <% @gigs.each do |gig| %>
                                        <tr>
                                                <td><%= link_to gig.title, gig %></td>
                                                <td><%= gig.date.strftime("%A, %e %B %Y") %></td>
                                                <td><%= gig.location %></td>
                                                <td>
                                                        <% if gig.date < Date.today %>
                                                                Archived
                                                        <% else %>
                                                                Upcoming
                                                        <% end %>
                                                </td>
                                                <td><%= link_to "Edit", edit_gig_path(gig), class: 'btn btn-warning' %></td>
                                                <td><%= link_to 'Destroy', gig, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                        </tr>
                                <% end %>
                        </tbody>
                </table>
        <% end %>
        <p><%= link_to "Add a gig", new_gig_path, class: 'btn btn-warning' %></p>

        <hr>

        <h2>Photos</h2>
        <% if @photos %>
                <%= link_to "Photo library", photos_path, class: 'btn btn-primary' %>
        <% end %>

        <%= link_to "Add a photo", new_photo_path, class: 'btn btn-warning' %>

        <hr>

        <h2>Albums</h2>
        <% if @albums.count > 0 %>
                <table class="table table-hover">
                        <thead>
                                <tr>
                                        <th>Title</th>
                                        <th>Tracks</th>
                                        <th></th>
                                        <th></th>
                                </tr>
                        </thead>
                        <tbody>
                                <% @albums.each do |album| %>
                                        <tr>
                                                <td><%= album.title %></td>
                                                <td>
                                                        <% if album.tracks.count > 0 %>
                                                                <% album.tracks.each do |track| %>
                                                                        <p><%= track.title %> [<%= link_to "Edit", edit_track_path(track) %>]</p>
                                                                <% end %>
                                                        <% end %>
                                                        <%= link_to "Add a track", new_track_path, class: 'btn btn-warning' %>
                                                </td>
                                                <td><%= link_to "Edit", edit_album_path(album), class: 'btn btn-warning' %></td>
                                        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                    </tr>
                                <% end %>
                        </tbody>
                </table>
        <% end %>
        <p><%= link_to "Add an album", new_album_path, class: 'btn btn-warning' %></p>

<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', signout_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', signin_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', admin_path %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bandrockr" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bandrockr" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>